language: node_js
node_js:
  - 14

script:
- echo "skipping tests"

deploy:
  provider: lambda
  function_name: "hello"
  region: "eu-central-1"
  role: "arn:aws:iam::419870347460:role/service-role/hello-role-i3tyjsgr"
  runtime: "nodejs14.x"
  handler_name: "handler"